trigger:
  batch: true
  branches:
    include:
    - '*'

pr: none

pool: quanby-lab

resources:
  repositories:
    - repository: quanby-lab
      type: github
      name: preinking/quanby-lab
      endpoint: github-quanby
      ref: refs/heads/main

variables:
  - template: pipelines/templates/ci-vars-template.yml@quanby-lab
    parameters:
      projectName: cert-manager-webhook-transip

steps:
  - template: pipelines/templates/ci-steps-template.yml@quanby-lab
    parameters:
      publishHelm: true
