---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-webhook-transip
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-transip:domain-solver
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
rules:
  - apiGroups:
      - cert-manager.webhook.transip
    resources:
      - '*'
    verbs:
      - 'create'
---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-webhook-transip:flowcontrol-solver
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
rules:
  - apiGroups:
      - "flowcontrol.apiserver.k8s.io"
    resources:
      - 'prioritylevelconfigurations'
      - 'flowschemas'
    verbs:
      - 'list'
      - 'watch'
---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-transip:auth-delegator
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-transip
    namespace: cert-manager
---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-transip:domain-solver
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-transip:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-webhook-transip:flowcontrol-solver
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-webhook-transip:flowcontrol-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-transip
    namespace: "cert-manager"
---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
# Grant cert-manager permission to read secrets from cert-manager ns (i.e. to read the api key for transip)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-webhook-transip:transip-auth
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
rules:
  - apiGroups:
      - ''
    resources:
      - 'secrets'
    verbs:
      - 'get'
---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-transip:webhook-authentication-reader
  namespace: kube-system
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-transip
    namespace: cert-manager
---
# Source: cert-manager-webhook-transip/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-webhook-transip:transip-auth
  namespace: cert-manager
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-manager-webhook-transip:transip-auth
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager-webhook-transip
    namespace: cert-manager
---
# Source: cert-manager-webhook-transip/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-transip
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: cert-manager-webhook-transip
    release: cert-manager-webhook-transip
---
# Source: cert-manager-webhook-transip/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-transip
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
spec:
  replicas: 
  selector:
    matchLabels:
      app: cert-manager-webhook-transip
      release: cert-manager-webhook-transip
  template:
    metadata:
      labels:
        app: cert-manager-webhook-transip
        release: cert-manager-webhook-transip
    spec:
      serviceAccountName: cert-manager-webhook-transip
      containers:
        - name: cert-manager-webhook-transip
          image: "quanby/cert-manager-webhook-transip:v1.20.1"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "cert-manager.webhook.transip"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: cert-manager-webhook-transip-webhook-tls
---
# Source: cert-manager-webhook-transip/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cert-manager.webhook.transip
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-transip-webhook-tls"
spec:
  group: cert-manager.webhook.transip
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-transip
    namespace: cert-manager
  version: v1alpha1
---
# Source: cert-manager-webhook-transip/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-transip-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
spec:
  secretName: cert-manager-webhook-transip-ca
  duration: 43800h # 5y
  issuerRef:
    name: cert-manager-webhook-transip-selfsign
  commonName: "ca.transip-webhook.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-transip/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-transip-webhook-tls
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
spec:
  secretName: cert-manager-webhook-transip-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: cert-manager-webhook-transip-ca
  dnsNames:
  - cert-manager-webhook-transip
  - cert-manager-webhook-transip.cert-manager
  - cert-manager-webhook-transip.cert-manager.svc
---
# Source: cert-manager-webhook-transip/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-transip-selfsign
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-transip/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-transip-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-transip
    chart: cert-manager-webhook-transip-v1.20.1
    release: cert-manager-webhook-transip
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-webhook-transip-ca
